language: minimal

# Retry installing nix due to nondeterministic error
#   Fatal error: glibc detected an invalid stdio handle
# see:
#   https://github.com/nh2/static-haskell-nix/pull/27#issuecomment-502652181
#   https://github.com/nixos/nix/issues/2733

install: |
  (for i in {1..5}; do bash <(curl https://nixos.org/nix/install) && exit 0; done; exit 1)
  . /home/travis/.nix-profile/etc/profile.d/nix.sh

env:
  global:
    - STABLE: "NIX_PATH=nixpkgs=https://github.com/nixos/nixpkgs-channels/archive/nixos-19.03.tar.gz"
    - UNSTABLE: "nixpkgs=https://github.com/nixos/nixpkgs-channels/archive/nixos-unstable.tar.gz"
  matrix:
    - PKG=banlist NIX_PATH=$STABLE
    - PKG=electrs NIX_PATH=$STABLE
    - PKG=hwi NIX_PATH=$STABLE
    - PKG=lightning-charge NIX_PATH=$STABLE
    - PKG=liquidd NIX_PATH=$STABLE
    - PKG=nanopos NIX_PATH=$STABLE
    - PKG=nodeinfo NIX_PATH=$STABLE
    - PKG=spark-wallet NIX_PATH=$STABLE
    - PKG=btcpayserver NIX_PATH=$STABLE
    - PKG=nbxplorer NIX_PATH=$STABLE

    - PKG=banlist NIX_PATH=$UNSTABLE
    - PKG=electrs NIX_PATH=$UNSTABLE
    - PKG=hwi NIX_PATH=$UNSTABLE
    - PKG=lightning-charge NIX_PATH=$UNSTABLE
    - PKG=liquidd NIX_PATH=$UNSTABLE
    - PKG=nanopos NIX_PATH=$UNSTABLE
    - PKG=nodeinfo NIX_PATH=$UNSTABLE
    - PKG=spark-wallet NIX_PATH=$UNSTABLE
    - PKG=btcpayserver NIX_PATH=$UNSTABLE
    - PKG=nbxplorer NIX_PATH=$UNSTABLE


script: nix-build -A $PKG

